frontend:
  image:
    repository: "nginx"
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer  # Exposes frontend to the internet
    port: 80
    targetPort: 80

backend:
  image:
    repository: "origenai/cloud-engineer-test-sample-app-backend"
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: ClusterIP    # Only accessible within the cluster
    port: 3001
    targetPort: 3001
  env:
    MONGODB_URI: "mongodb://mongodb-service:27017/mydatabase"

mongodb:
  image:
    repository: mongo
    tag: 6.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP    # Only accessible within the cluster
    port: 27017
  persistence:
    enabled: true
    size: 10Gi
  auth:
    rootPassword: "" 