frontend:
  image:
    repository: origenai/cloud-engineer-test-sample-app-frontend
    tag: 1.0.0
  service:
    type: LoadBalancer  # Exposes frontend to the internet
    port: 80
    targetPort: 80

backend:
  image:
    repository: origenai/cloud-engineer-test-sample-app-backend
    tag: 1.0.0
  service:
    type: ClusterIP    # Only accessible within the cluster
    port: 8080
    targetPort: 8080
  env:
    MONGODB_URI: "mongodb://mongodb-service:27017/mydatabase"

mongodb:
  image:
    repository: mongo
    tag: 6.0
  service:
    type: ClusterIP    # Only accessible within the cluster
    port: 27017
  persistence:
    size: 10Gi
  auth:
    rootPassword: "pass123" 